#!/bin/bash
########################################################
#
# Copyright 2014, All Rights Reserved.
#
# Code licensed under the MIT LICENSE:
# https://github.com/randsonjs/dotfiles/blob/master/LICENSE
#
# @author Randson Oliveira <randsonjs@gmail.com>
#
########################################################

# Create your here: http://patorjk.com/software/taag/#p=display&f=Graffiti&t=Type%20Something%20
msg ' __    __    __  __        _____     ______    ______   ______   __     __         ______     ______    '
msg '/\ "-./  \  /\ \_\ \      /\  __-.  /\  __ \  /\__  _\ /\  ___\ /\ \   /\ \       /\  ___\   /\  ___\   '
msg '\ \ \-./\ \ \ \____ \     \ \ \/\ \ \ \ \/\ \ \/_/\ \/ \ \  __\ \ \ \  \ \ \____  \ \  __\   \ \___  \  '
msg ' \ \_\ \ \_\ \/\_____\     \ \____-  \ \_____\   \ \_\  \ \_\    \ \_\  \ \_____\  \ \_____\  \/\_____\ '
msg '  \/_/  \/_/  \/_____/      \/____/   \/_____/    \/_/   \/_/     \/_/   \/_____/   \/_____/   \/_____/ '
msg '                                                                                                        '

## Variables
dir=~
dotfiles="$dir/.dotfiles"

echo "[?] Which computer name would you like to use?"
read computer_name

echo "[?] Which Git name would you like to use?"
read git_username

echo "[?] Which Git email would you like to use?"
read git_email

echo "[?] Which editor would you like to use?"
read user_editor

echo "[?] Which Oh My Zsh theme would you like to use?"
read oh_my_zsh_theme

## Import files from install directory
source install/install
