#!/bin/bash
########################################################
#
# Copyright 2014, All Rights Reserved.
#
# Code licensed under the MIT LICENSE:
# https://github.com/randsonjs/dotfiles/blob/master/LICENSE
#
# @author Randson Oliveira <randsonjs@gmail.com>
#
########################################################

# Create your here: http://patorjk.com/software/taag/#p=display&f=Graffiti&t=Type%20Something%20
echo '  _____     ______    ______   ______   __     __         ______     ______    '
echo ' /\  __-.  /\  __ \  /\__  _\ /\  ___\ /\ \   /\ \       /\  ___\   /\  ___\   '
echo ' \ \ \/\ \ \ \ \/\ \ \/_/\ \/ \ \  __\ \ \ \  \ \ \____  \ \  __\   \ \___  \  '
echo '  \ \____-  \ \_____\   \ \_\  \ \_\    \ \_\  \ \_____\  \ \_____\  \/\_____\ '
echo '   \/____/   \/_____/    \/_/   \/_/     \/_/   \/_____/   \/_____/   \/_____/ '
echo '                                                                                                        '

## Variables
dir=~
dotfiles="$dir/.dotfiles"

echo "[?] What is your BI? [32bits or 64bits]"
read BI

echo "[?] Which Git name would you like to use?"
read git_username

echo "[?] Which Git email would you like to use?"
read git_email

######################################################## Essentials

### cURL
sudo apt-get install curl

### php5-cli
sudo apt-get install php5-cli

### php5
sudo apt-get install php5

### mysql-server
sudo apt-get install mysql-server

### apache2
sudo apt-get install apache2

### php5-mcrypt
sudo apt-get install php5-mcrypt

### phpmyadmin
sudo apt-get install phpmyadmin

### mysql workbench
sudo apt-get install mysql-workbench

### Popcorn Time
sudo add-apt-repository ppa:webupd8team/popcorntime
sudo apt-get update
sudo apt-get install popcorn-time

######################################################## Shell

### GIT
sudo apt-get install libcurl4-gnutls-dev libexpat1-dev gettext \
  libz-dev libssl-dev
sudo apt-get install git
sudo git config --global user.name "$git_username"
sudo git config --global user.email "$git_email"
sudo git config --global color.ui auto

### ZSH
sudo apt-get install zsh
sudo apt-get install git-core

### Oh My ZSH
wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh
chsh -s `which zsh`

######################################################## Editors

### Sublime Text 3
sudo add-apt-repository ppa:webupd8team/sublime-text-3
sudo apt-get update
sudo apt-get install sublime-text-installer

######################################################## Themes

### Dracula Theme for ZSH
git clone https://github.com/zenorocha/dracula-theme/
sudo mv dracula-theme/zsh/dracula.zsh-theme ~/.oh-my-zsh/themes/dracula.zsh-theme
sudo rm -r draculda-theme
sudo cp templates/.zsh ~/.zshrc


### Dracula Color Scheme Sublime Text 3
git clone https://github.com/zenorocha/dracula-theme/ "Dracula Color Scheme"
sudo mv Dracula\ Color\ Scheme ~/.config/sublime-text-3/Packages

### Spacegray Theme Sublime Text 3
git clone https://github.com/kkga/spacegray.git "Theme - Spacegray"
sudo mv Theme\ -\ Spacegray ~/.config/sublime-text-3/Packages/

# Copy sublime preferences for correct directory
sudo cp templates/Preferences-sublime-settings ~/.config/sublime-text-3/Packages/User/Preferences.sublime-settings

# st3 package control plugin
curl https://sublime.wbond.net/Package%20Control.sublime-package -o ~/.config/sublime-text-3/Installed\ Packages/Package\ Control.sublime-package

######################################################## General

### Skype
sudo apt-get install libqt4-dbus libqt4-network libqt4-xml libasound2
if [ "$BI" -eq 64 ]; then
  wget http://www.skype.com/go/getskype-linux-beta-ubuntu-64
else
  wget http://www.skype.com/go/getskype-linux-beta-ubuntu-32
fi

sudo dpkg -i getskype-*
sudo apt-get -f install

### Numix
sudo add-apt-repository ppa:numix/ppa
sudo apt-get update
sudo apt-get install numix-gtk-theme
sudo apt-get update
sudo apt-get install numix-icon-theme-circle

### Plank
sudo add-apt-repository ppa:ricotz/docky
sudo apt-get update
sudo apt-get install plank

### MokaIcon
sudo add-apt-repository ppa:moka/stable
sudo apt-get update
sudo apt-get install moka-icon-theme

### Unity Tweak Tool
sudo add-apt-repository ppa:freyja-dev/unity-tweak-tool-daily
sudo apt-get update
sudo apt-get install unity-tweak-tool

### Clementine
sudo apt-get install clementine

### Chromium Browser
sudo apt-get install chromium-browser

### Google Chrome Browser
sudo apt-get install libxss1 libappindicator1 libindicator
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome*.deb
sudo rm google-chrome-stable_current_amd64.deb

### Filezilla
sudo apt-get install filezilla

### VLC Media Player
sudo apt-get install vlc

### Adobe Flash Player Plugin
sudo apt-get install adobe-flashplugin

### Pidgin
sudo add-apt-repository -y ppa:pidgin-developers/ppa
sud apt-get update
sudo apt-get install pidgin

### GParted
sudo apt-get install gparted

### gitg
sudo apt-get install gitg

### Virtual Box
sudo apt-get install virtualbox

### Caffeine
sudo add-apt-repository ppa:caffeine-developers/ppa
sudo apt-get update
sudo apt-get install caffeine

######################################################## NodeJS

### NodeJS
curl -sL https://deb.nodesource.com/setup | sudo bash -
sudo apt-get install nodejs

### Bower
sudo npm install -g bower

### Grunt CLI
sudo npm install -g grunt-cli

### NodeGH
sudo npm install -g gh

### Gulp
sudo npm install -g gulp

### JSHint
sudo npm install jshint

### Express
sudo npm install -g express-generator

### HarpJS
sudo npm install -g harp

######################################################## Ruby

### Ruby
sudo apt-get install ruby ruby-dev make

###w Jekyll
sudo gem install jekyll --no-rdoc --no-ri

######################################################## PHP

### Composer
curl -sS https://getcomposer.org/installer | php
sudo mv composer.phar /usr/local/bin/composer

### PHPUnit
wget https://phar.phpunit.de/phpunit.phar
chmod +x phpunit.phar
sudo mv phpunit.phar /usr/local/bin/phpunit
phpunit --version

######################################################## GitHub

### xclip - generate ssh key for github
ssh-keygen -t rsa -C "$git_email"
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_rsa
sudo apt-get install xclip
xclip -sel clip < ~/.ssh/id_rsa.pub

# Tell ubuntu to do nothing when I close my laptop lid
# http://askubuntu.com/questions/15520/how-can-i-tell-ubuntu-to-do-nothing-when-i-close-my-laptop-lid
